version: '3.9'
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - app-network

  app:
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge