version: '3.9'
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s